apiVersion: v2
appVersion: 24.3.2
description: A helm chart for Tock. Tock is an open conversational AI platform. It's a complete solution to build conversational agents aka bots.Tock can integrate and experiment with both classic and Generative AI (LLM, RAG) models
name: tock
type: application
version: 0.4.1


maintainers:
  - name: stephanacquatella

dependencies:
- name: mongodb
  version: 13.6.8
  #version: 14.8.3
  repository : https://charts.bitnami.com/bitnami
  condition: global.deployMongoDb.enabled
  tags: 
    - mongodb

- name: opensearch
  version: 2.20.0
  repository : https://opensearch-project.github.io/helm-charts/
  condition: global.deployOpenSearch.enabled
  tags: 
    - opensearch