apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-bot-api'
  labels:
    app.kubernetes.io/name: bot-api
    app.kubernetes.io/component: bot-api
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.botApi.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.botApi.service.type }}
  selector:
    app.kubernetes.io/component: bot-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: port-8080
