apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-bot-api'
  labels:
    app.kubernetes.io/name: bot-api
    app.kubernetes.io/component: bot-api
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.botApi.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: bot-api
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/resource: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/component: bot-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/resource: deployment
    spec:
      {{- include "botApi.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.botApi.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.botApi.podSecurityContext "enabled" | toYaml | nindent 10 }}
      {{- end }}
      initContainers:
        - name: check-mongo
          image: {{ include "initContainer.image" . }}
          {{- if .Values.global.initContainerImage.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.global.initContainerImage.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking mongo port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ template "url.mongo.isup" . }} 27017 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      {{- if .Values.botApi.resources }}
          resources: {{- toYaml .Values.botApi.resources | nindent 12 }}
      {{- end }}  
        - name: check-nlp-api
          image: {{ include "initContainer.image" . }}
          {{- if .Values.global.initContainerImage.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.global.initContainerImage.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking nlp-api port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-nlp-api 8080 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      {{- if .Values.botApi.resources }}
          resources: {{- toYaml .Values.botApi.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: bot-api
          image: {{ include "botApi.image" . }}
          {{- if .Values.botApi.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.botApi.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: bot-api
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 5 # Defaults to 1
            periodSeconds: 20 # Defaults to 10
            failureThreshold: 3 # Defaults to 3
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-bot-api-cfg'
          {{- if .Values.botApi.resources }}
          resources: {{- toYaml .Values.botApi.resources | nindent 14 }}
          {{- end }}
    {{- with .Values.botApi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.botApi.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.botApi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}