apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-duckling'
  labels:
    app.kubernetes.io/name: duckling
    app.kubernetes.io/component: admin-web
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/component: duckling
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: port-8080
