apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-genai-orchestrator'
  labels:
    app.kubernetes.io/name: genai-orchestrator
    app.kubernetes.io/component: genai-orchestrator
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: genai-orchestrator
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/resource: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/component: genai-orchestrator
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/resource: deployment
    spec:
      {{- include "genAiOrchestrator.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.genAiOrchestrator.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.genAiOrchestrator.podSecurityContext "enabled" | toYaml | nindent 10 }}
      {{- end }}
      containers:
        - name: genai-orchestrator
          image: {{ include "genAiOrchestrator.image" . }}
          {{- if .Values.genAiOrchestrator.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.genAiOrchestrator.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: genaiport
              containerPort: 8000
#          livenessProbe:
#            httpGet:
#              path: /healthcheck
#              port: 8000
#            initialDelaySeconds: 180
#            timeoutSeconds: 5 # Defaults to 1
#            periodSeconds: 20 # Defaults to 10
#            failureThreshold: 3 # Defaults to 3
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-genai-orchestrator-cfg'
      {{- if .Values.genAiOrchestrator.resources }}
          resources: {{- toYaml .Values.genAiOrchestrator.resources | nindent 14 }}
      {{- end }} 
    {{- with .Values.genAiOrchestrator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.genAiOrchestrator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.genAiOrchestrator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}