apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-kotlin-compiler'
  labels:
    app.kubernetes.io/name: kotlin-compiler
    app.kubernetes.io/component: kotlin-compiler
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kotlin-compiler
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/resource: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kotlin-compiler
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/resource: deployment
    spec:
      {{- include "kotlinCompiler.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.kotlinCompiler.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.kotlinCompiler.podSecurityContext "enabled" | toYaml | nindent 10 }}
      {{- end }}
      containers:
        - name: kotlin-compiler
          image: {{ include "kotlinCompiler.image" . }}
          {{- if .Values.kotlinCompiler.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.kotlinCompiler.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: kotlin-compiler
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 5 # Defaults to 1
            periodSeconds: 20 # Defaults to 10
            failureThreshold: 3 # Defaults to 3
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-kotlin-compiler-cfg'
      {{- if .Values.kotlinCompiler.resources }}
          resources: {{- toYaml .Values.kotlinCompiler.resources | nindent 14 }}
      {{- end }} 
    {{- with .Values.kotlinCompiler.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.kotlinCompiler.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.kotlinCompiler.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}