apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-web-auth-cfg
  labels:
    app.kubernetes.io/name: admin-web-auth
    app.kubernetes.io/component: admin-web
data:
  tock_users:  "alice@tock.ai,bob@tock.ai" # Identifiants (séparés par des virgules). Valeur par defaut `admin@app.com`
  tock_passwords: "secret1,secret2" # Mots de passe (séparés par des virgules). Valleur par defaut `password`` 
  tock_organizations: "tock,tock" # Organisations (séparées par des virgules). Valleur par defaut `app``
  tock_roles: "botUser,nlpUser|botUser|admin|technicalAdmin" #  Rôles séparés par des | (puis par des virgules). Valeur par defaut vide , Dans cet exemple, Alice a le rôle botUser, alors que Bob a tous les rôles.