
global:
  wildcardDomain: rancher.localhost
  deployMongoDb:
    enabled: true

botApi:
  ingress:
    enabled: true

adminWeb:
  ingress:
    enabled: true
  authCongifMap: "admin-web-auth-cfg"

mongodb:
  architecture: "replicaset"
  replicaCount: 1
  auth:
    enabled: false
 #   rootUser: root  # default is root
 #   rootPassword: myroopaas
  persistence:
    enabled: true
    size: 1Gi
  image:
    repository: zcube/bitnami-compat-mongodb
    tag: 6.0.5